# Generated by Django 2.1.7 on 2019-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190414_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
